### ISSUE TITLE
exe

### ISSUE THREAD

**Issue by zeus1921** [pintoso/Agent-Picker#1]
there's no .exe on the zip dude.

**Comment by pintoso** [comment]
look the release area
![image](https://user-images.githubusercontent.com/26844778/83951612-f0b7bf00-a808-11ea-9d23-99929591adeb.png)

**Comment by zeus1921** [comment]
Ahhh thanks bud

A sábado, 6/06/2020, 19:19, PINTOSO <notifications@github.com> escreveu:
