### ISSUE TITLE
2.0 support.

### ISSUE THREAD

**Issue by Doubs115** [pintoso/Agent-Picker#3]
2.0 has a layout that consists of 2 rows and a new agent. They may add more agents and rows for the agents later in the game as well.

**Comment by pintoso** [comment]
I'm currently busy with other projects and I don't have the game installed right now.
I will leave the issue open, when I have time I will fix it and close the issue.

Thanks for letting me know ^^

**Comment by Doubs115** [comment]
no problem

**Comment by pintoso** [comment]
thanks for waiting, everything has been fixed and improved!
